---
- hosts: localhost
  vars:
    list1: ['Template iterate','Template loop','Template item']
  tasks:
    - name: Ansible template loop example.
      template:
        src: jinja2TemplateLoop.j2
        dest: /opt/DevOps/Ansible_ConfigurationScripts/output.txt
        mode: 0777
